author: Rakuten Group, Inc.
module: RAnalytics
module_version: 10.0.0
readme: README.md
documentation: "{CHANGELOG.md,CONTRIBUTING.md,ADVANCED_USAGE.md}"
hide_documentation_coverage: true
copyright: "© Rakuten Group, Inc."
podspec: RAnalytics.podspec
xcodebuild_arguments:
  - -workspace
  - RakutenAnalyticsSDK/RakutenAnalyticsSDK.xcworkspace
  - -scheme
  - RAnalytics
