author: Rakuten Group, Inc.
module: RakutenAnalytics
module_version: 10.5.0
readme: README.md
documentation: "{CHANGELOG.md,CONTRIBUTING.md,ADVANCED_USAGE.md}"
hide_documentation_coverage: true
copyright: "© Rakuten Group, Inc."
podspec: RakutenAnalytics.podspec
xcodebuild_arguments:
  - -workspace
  - RakutenAnalyticsSDK/RakutenAnalyticsSDK.xcworkspace
  - -scheme
  - RakutenAnalytics
