workspace 'UnitTestApp.xcworkspace'

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Common' do

	pod 'RAnalyticsBroadcast', :inhibit_warnings => false, :path => '../RAnalyticsBroadcast.podspec'

target 'UnitTests'
target 'FunctionalTests'
target 'IntegrationTests'

end
