workspace 'UnitTestApp.xcworkspace'

platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Common' do

	pod 'RAnalyticsBroadcast', :inhibit_warnings => false, :path => '../RAnalyticsBroadcast.podspec'

target 'UnitTests'
target 'FunctionalTests'
target 'IntegrationTests'

end

post_install do |installer|
  ['Pods_Common_UnitTests', 'Pods_Common_FunctionalTests', 'Pods_Common_IntegrationTests'].each do |target_name|
    if target = installer.pods_project.targets.find { |t| t.name == target_name }
      target.build_configurations.each do |config|
        config.build_settings['GCC_INSTRUMENT_PROGRAM_COVERAGE'] = 'YES'
        config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'YES'
      end
    end
  end
end
