/*
 * © Rakuten, Inc.
 * authors: "Rakuten Ecosystem Mobile" <ecosystem-mobile@mail.rakuten.com>
 */
#import <RSDKAnalytics/RSDKAnalyticsDefines.h>
#import <RSDKAnalytics/RSDKAnalyticsManager.h>
#import <RSDKAnalytics/RSDKAnalyticsRecord.h>
#import <RSDKAnalytics/RSDKAnalyticsItem.h>
#import <RSDKAnalytics/RSDKAnalyticsEvent.h>
#import <RSDKAnalytics/RSDKAnalyticsState.h>
#import <RSDKAnalytics/RSDKAnalyticsRATTracker.h>


/// @name Environment

/**
 * Version of this library.
 *
 * @note This value is sent as the **ver** (`VERSION`) RAT parameter
 * and is used as a protocol version by the server-side parsers. See the
 * [RAT Generic IDL](https://git.rakuten-it.com/projects/RG/repos/rg/browse/ratGeneric.idl)
 * for more information.
 *
 * @ingroup AnalyticsConstants
 * @since 2.0.0
 */
RSDKA_EXPORT const NSString* const RSDKAnalyticsVersion;

/**
 * Domain of errors generated by the RSDKAnalytics library.
 *
 * @ingroup AnalyticsConstants
 */
RSDKA_EXPORT NSString *const RSDKAnalyticsErrorDomain;

/**
 * Enumeration of RSDKAnalytics errors.
 * All these errors belong under the #RSDKAnalyticsErrorDomain domain.
 *
 * @enum RSDKAnalyticsError
 * @ingroup AnalyticsConstants
 */
typedef NS_ENUM(NSInteger, RSDKAnalyticsError)
{
    /**
     *  Error if a tracker is already registered.
     */
    RSDKAnalyticsTrackerAlreadyPresentError RSDKA_SWIFT3_NAME(RSDKAnalyticsError.trackerAlreadyPresent)
};

#ifdef DOXYGEN
    /**
     * @defgroup AnalyticsConstants Constants and enumerations
     */
#endif

