source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git'

workspace 'RSDKAnalyticsSample.xcworkspace'

platform :ios, "10.0"
use_frameworks!

abstract_target 'Common' do
  pod 'RAnalytics', :path => '../../RAnalytics.podspec'
  pod 'RDeviceIdentifier', :inhibit_warnings => true, :git => 'https://gitpub.rakuten-it.com/scm/eco/ios-deviceid.git'

  target 'RSDKAnalyticsSample' do
    pod 'FXForms',                    '~> 1.2'
    pod 'SVProgressHUD',              '~> 1.0'
    pod 'RESideMenu',                 '~> 4.0'
    # Latest publish version, 2.2, still suffers from https://github.com/PrideChung/FontAwesomeKit/issues/26
    # The fix has been mrged, tho, so we're using the currently-latest commit
    pod 'FontAwesomeKit/FontAwesome', :git => 'https://github.com/PrideChung/FontAwesomeKit', :commit => 'ffcc61b71c'
  end

  target 'RSDKAnalyticsSampleSwift' do
  end

  target 'AnalyticsTodayExt' do
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
