# this plugin is used in order to build the Pod library as static even if it contains swift code
# This fixes this error:
# "Using Swift static libraries with custom module maps is currently not supported. Please build `RAnalytics` as a framework or remove the custom module map."
# https://github.com/joncardasis/cocoapods-user-defined-build-types
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!

source 'https://cdn.cocoapods.org/'
source 'https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git'

platform :ios, '11.0'
inhibit_all_warnings!

workspace 'RakutenAnalyticsSDK'

target 'RAnalytics' do
  pod 'RLogger', '~> 1.0', :build_type => :static_framework
  pod 'RDeviceIdentifier', :build_type => :static_framework
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
