source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git'

platform :ios, '11.4'
inhibit_all_warnings!

workspace 'RakutenAnalyticsSDK'

target 'RAnalytics' do
  pod 'RAnalytics', :inhibit_warnings => false, :path => '../RAnalytics.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.4'
    end
  end
end
