workspace 'RakutenAnalyticsSample.xcworkspace'

platform :ios, "15.0"
use_frameworks!

abstract_target 'Common' do

  # Source-based pod of ../RakutenAnalytics for local development
  pod 'RakutenAnalytics', :path => '../RakutenAnalytics.podspec'

  # GitHub pod
  # pod 'RakutenAnalytics'
  
  target 'RakutenAnalyticsSamplePod'
end
