source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git'

workspace 'Samples.xcworkspace'
project 'RSDKAnalyticsSample/RSDKAnalyticsSample.xcodeproj'

platform :ios, "8.0"
use_frameworks!

target 'RSDKAnalyticsSample' do
  pod 'RSDKAnalytics', :path => '../RSDKAnalytics.podspec'

  pod 'FXForms',                    '~> 1.2'
  pod 'SVProgressHUD',              '~> 1.0'
  pod 'RESideMenu',                 '~> 4.0'
  # Latest publish version, 2.2, still suffers from https://github.com/PrideChung/FontAwesomeKit/issues/26
  # The fix has been mrged, tho, so we're using the currently-latest commit
  pod 'FontAwesomeKit/FontAwesome', :git => 'https://github.com/PrideChung/FontAwesomeKit', :commit => 'ffcc61b71c'
  pod 'HockeySDK',                  '~> 3.8'

end

# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
