workspace 'RAnalyticsSample.xcworkspace'

platform :ios, "12.0"
use_frameworks!

abstract_target 'Common' do

  # Source-based pod of ../RakutenAnalytics for local development
  pod 'RakutenAnalytics', :path => '../RakutenAnalytics.podspec'

  # GitHub pod
  # pod 'RakutenAnalytics'
  
  target 'RAnalyticsSample'
  target 'RAnalyticsSampleDest'
  target 'RAnalyticsSampleSwiftUI'
  target 'AnalyticsTodayExt'
end
