# Import base_config from git
import_from_git(url: 'https://gitpub.rakuten-it.com/scm/eco/ci-fastlane.git')

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    shared_ci(options)
  end
end

# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
