opt_out_usage
#update_fastlane
fastlane_version "1.37.0"

default_platform :ios
platform :ios do
  before_all do
    get_changelog_from_git
    get_version_from_date
  end

  desc "Run unit tests"
  lane :tests do |options|
    cocoapods
    scan(
      clean: true,
      skip_build: true,
      output_directory: './artifacts/unit-tests',
      scheme: 'Tests',
      device: 'REM SDK Unit Tests',
      code_coverage: true)
    # Doesn't work for now
    #xcov(
    #  include_test_targets: true,
    #  project: 'Pods/Pods.xcodeproj',
    #  derived_data_path: "#{Dir.pwd}/../build/RSDKAnalytics",
    #  scheme: 'RSDKAnalytics',
    #  output_directory: './artifacts/coverage')
  end

  desc "Build a sample"
  lane :sample do |options|

    # Increment version
    increment_build_number(build_number: lane_context[SharedValues::R_VERSION_FROM_DATE], xcodeproj: "Samples/RSDKAnalyticsSample/RSDKAnalyticsSample.xcodeproj")
    increment_version_number(version_number: lane_context[SharedValues::R_VERSION_FROM_DATE], xcodeproj: "Samples/RSDKAnalyticsSample/RSDKAnalyticsSample.xcodeproj")

    # Install pods
    cocoapods(podfile: "Samples/Podfile", repo_update: false)

    # Build sample
    gym(
      output_directory: './artifacts/device',
      workspace: "Samples/Samples.xcworkspace",
      provisioning_profile_path: 'fastlane/R_Enterprise5th_161102.mobileprovision',
      codesigning_identity: 'iPhone Distribution',
      export_method: 'enterprise',
      export_team_id: '5J4GVGN58B',
      scheme: 'RSDKAnalyticsSample')

    hockey(
      api_token: '1f6056ff485f410d856f0bca668c2c07',
      notes_type: '0',
      notes: lane_context[SharedValues::R_CHANGELOG_FROM_GIT])
  end

  desc "Build everything"
  lane :ci do |options|
    ENV['FL_COCOAPODS_VERBOSE'] = "1"

    tests(options)
    sample(options)
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
