name: Mirror Repo Main
on:
  push:
    branches:
      - "master"
jobs:
  push-repo:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: git push to GitPub
      env:
        GITPUB_REMOTE: ssh://git@gitpub.rakuten-it.com:7999/eco/core-ios-analytics.git
        TARGET_BRANCH: master
      run: |
        git remote add gitpub $GITPUB_REMOTE || echo Remote already added
        git push gitpub "refs/remotes/origin/$TARGET_BRANCH:refs/heads/$TARGET_BRANCH"
        git push gitpub "refs/tags/*:refs/tags/*" || true
